const MOVIES_API_URL = "https://api.nomoreparties.co/beatfilm-movies";
const MAIN_API_URL = "https://api.amoiseeva.students.nomoredomains.sbs";
const MOVIES_IMAGE_URL = "https://api.nomoreparties.co";

const SHORT_MOVIE = 40;
const MINUTES_IN_HOUR = 60;

const CARDS_COUNT_MAX_WINDOW_SIZE = 4;
const CARDS_COUNT_MIN_WINDOW_SIZE = 5;

const CARDS_NEXT_COUNT_MAX_WINDOW_SIZE = 3;
const CARDS_NEXT_COUNT_MEDIUM_WINDOW_SIZE = 2;
const CARDS_NEXT_COUNT_MIN_WINDOW_SIZE = 1;

const MAX_WINDOW_SIZE = 1280;
const MEDIUM_WINDOW_SIZE = 768;
const MIN_WINDOW_SIZE = 320;

export {
  MOVIES_API_URL,
  MAIN_API_URL,
  MOVIES_IMAGE_URL,
  SHORT_MOVIE,
  MINUTES_IN_HOUR,
  CARDS_COUNT_MAX_WINDOW_SIZE,
  CARDS_COUNT_MIN_WINDOW_SIZE,
  CARDS_NEXT_COUNT_MAX_WINDOW_SIZE,
  CARDS_NEXT_COUNT_MEDIUM_WINDOW_SIZE,
  CARDS_NEXT_COUNT_MIN_WINDOW_SIZE,
  MAX_WINDOW_SIZE,
  MEDIUM_WINDOW_SIZE,
  MIN_WINDOW_SIZE,
};
